parameters:

services:
    catalog.catalog_menu_listener:
        class: VG\WebBundle\Listener\CatalogMenuListener
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    catalog.catalog_menu_extension:
        class: VG\WebBundle\Extension\CatalogMenuExtension
        arguments:
            - @catalog.catalog_menu_listener
        tags:
            - { name: twig.extension }

    util.contacthelper:
      class: VG\WebBundle\Util\ContactHelper
      arguments:
        serviceContainer: "@service_container"
    contact_form_ask_listener:
        class: VG\WebBundle\Listener\AskListener
        calls:
            - [setContactHelper, [@util.contacthelper]]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    contact_form_ask_extension:
        class: VG\WebBundle\Extension\AskExtension
        arguments:
            - @contact_form_ask_listener
        tags:
            - { name: twig.extension }
