parameters:
#    bionic_university_user.example.class: VG\UserBundle\Example

services:
    vg.admin.param:
        class: VG\AdminBundle\Admin\ParamAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Параметры, label: Параметры }
        arguments:
            - ~
            - VG\WebBundle\Entity\Param
            - 'VGAdminBundle:ParamAdmin'

    vg.admin.user:
        class: VG\AdminBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Пользователи, label: Админы }
        arguments:
            - ~
            - VG\UserBundle\Entity\User
            - 'VGAdminBundle:UserAdmin'

    vg.admin.article:
        class: VG\AdminBundle\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Контент, label: Текстовый материал }
        arguments:
            - ~
            - VG\ContentBundle\Entity\Article
            - 'VGAdminBundle:ArticleAdmin'
    vg.admin.section:
        class: VG\AdminBundle\Admin\SectionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Магазин, label: Категории товаров }
        arguments:
            - ~
            - VG\CatalogBundle\Entity\Section
            - 'VGAdminBundle:SectionAdmin'
    vg.admin.product:
        class: VG\AdminBundle\Admin\ProductAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Магазин, label: Товары}
        arguments:
            - ~
            - VG\ProductBundle\Entity\Product
            - SonataAdminBundle:CRUD
        calls:
            - [ setEntityManager, [ '@doctrine.orm.entity_manager' ] ]

    vg.admin.product_image:
        class: VG\AdminBundle\Admin\ProductImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Магазин, label: Катринки, show_in_dashboard: false }
        arguments:
            - ~
            #- Application\Sonata\MediaBundle\Entity\Media
            - VG\ProductBundle\Entity\ProductImage
            - 'VGAdminBundle:ProductImageAdmin'

    vg.admin.manufacturer:
        class: VG\AdminBundle\Admin\ManufacturerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Магазин, label: Производители }
        arguments:
            - ~
            - VG\CatalogBundle\Entity\Manufacturer
            - 'VGAdminBundle:ManufacturerAdmin'


