parameters:
#    bionic_university_user.example.class: VG\UserBundle\Example

services:
    vg.admin.article:
        class: VG\AdminBundle\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: nanosvet, label: Текстовый материал }
        arguments:
            - ~
            - VG\ContentBundle\Entity\Article
            - 'VGAdminBundle:ArticleAdmin'